version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # Porta padrão do Redis
    volumes:
      - redis_data:/data # Persistência de dados
    command: ["redis-server", "--appendonly", "yes"] # Habilita persistência AOF
    restart: always

volumes:
  redis_data:
